### ISSUE TITLE
Shiny Hunter not working

### ISSUE THREAD

**Issue by SKukreja** [shalzuth/TemSharp#1]
Using the latest version with these changes https://github.com/shalzuth/TemSharp/commit/0001696665581acab58c585e16a97f4e6442b68e

Shiny Hunter when ticked will stand in place and somehow trigger a battle, then do nothing and untick itself.

**Comment by D3XX3R** [comment]
shalzuth fixed it in cd9e3f7

**Comment by SKukreja** [comment]
Confirmed fixed
