### ISSUE TITLE
Make a disclaimer (Temtem permanent ban)

### ISSUE THREAD

**Issue by WirBleibenDrin** [shalzuth/TemSharp#15]
Please make a disclaimer that says that you might get banned for using this tool.
I don't know if I'm the first one who got banned for using this tool.
![image](https://user-images.githubusercontent.com/60635524/73709119-84b13700-4700-11ea-89e8-64d686c3128e.png)

**Comment by shalzuth** [comment]
I disabled all hacks that can cause ban.
