### ISSUE TITLE
Open Shop with more Items

### ISSUE THREAD

**Issue by stevenklar** [shalzuth/TemSharp#4]
Hey, first of all, great work. :-)

After crawling the code a bit I noticed that "Open Shop" already had other items prepared.
Is there a reason you only added catch items? Did you actually try?

**Comment by PuskyWasTaken** [comment]
I just checked this myself.. It works for any shop items. Just uncomment the items you want and recompile the project.

**Comment by stevenklar** [comment]
Thought so. Thanks for checking, will compile it myself then. But maybe there is a reason why commented it out?

**Comment by stevenklar** [comment]
Opened PR for this #11

**Comment by shalzuth** [comment]
#11
