### ISSUE TITLE
Heal not working 

### ISSUE THREAD

**Issue by wsoxfan1214** [shalzuth/TemSharp#6]
The setting doesn't seem to do anything, even out of battle. Is there a step beyond just enabling this setting, or is this busted at the moment?

**Comment by PuskyWasTaken** [comment]
Works for me. It should only work out of battle. Try pressing the button twice maybe? (toggle + untoggle).

**Comment by wsoxfan1214** [comment]
By "the button", you mean just disabling and re-enabling?
