### ISSUE TITLE
Need Help with automating catching.

### ISSUE THREAD

**Issue by PuskyWasTaken** [shalzuth/TemSharp#7]
Basically, been trying to do this for a bit but the most I could do is open the inventory and selecting the temcard for now.
Don't really know how to select the target temtem.
Anyone interested in doing this?

**Comment by Marvin1412** [comment]
Last time i coded was long ago, but this should be a specific order so it is pretty easy to write a simple line of keyboard commands, i can't look it up right now but since it is always fixed positions throwing cards is quiet easy, getting the TemTem on the right hp is harder.
